### ISSUE TITLE
Market Page

### ISSUE THREAD

**Issue by UTBExchange** [deganDev/utbexchange#1]
1. In market page, each market heading should be left align
![market](https://user-images.githubusercontent.com/35572056/35444955-f5bfdafc-02d1-11e8-91f4-3c37ac4b6699.png)

**Comment by zohaibqadir** [comment]
2. Make Logo clickable and it will redirected to Home page:
@zahidmahmood12  FYI

**Comment by deganDev** [comment]
2. Make Logo Clickable and redirected it to Home page:
@zahidmahmood12 fyi

**Comment by zahidmahmood12** [comment]
FIX: 
![image](https://user-images.githubusercontent.com/35915987/35734424-e85aa8c6-0842-11e8-85c3-31ff982c1e94.png)
