### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by UTBExchange** [deganDev/utbexchange#2]
1. Sign Up now button is interacting with bottom section
![sketch](https://user-images.githubusercontent.com/35572056/35445188-9cf4849e-02d2-11e8-90c0-5c969a832c16.png)

**Comment by deganDev** [comment]
2. Removal of extra links and sections:
@zahidmahmood12, Please remove all extra links and sections(roadmap etc) from the home page

**Comment by zahidmahmood12** [comment]
FIX:
![image](https://user-images.githubusercontent.com/35915987/35734346-9d31d144-0842-11e8-8883-a3c85cb9d15f.png)
