### ISSUE TITLE
Logo Update:

### ISSUE THREAD

**Issue by deganDev** [deganDev/utbexchange#4]
@zahidmahmood12 Please update the logo and make it clickable... If customer click on the image then he will redirected to home page..
[Fwd_UTB_Logo_Attached.zip](https://github.com/zohaibqadir/utbexchange/files/1689084/Fwd_UTB_Logo_Attached.zip)

**Comment by zahidmahmood12** [comment]
FIX: 
![image](https://user-images.githubusercontent.com/35915987/35734261-5788a550-0842-11e8-86d1-8d4cb9cc2f1d.png)
